spring.datasource.url=jdbc:mysql://localhost:3306/pbl3_project_demo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.jpa.show-sql=false
app.demo.seed=true
