package com.pbl3.project.pbl3_project.entity;

public enum OperationalAuditAction {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    ORDER_CREATED,
    ORDER_CANCELED,
    ORDER_RETURNED,
    IMPORT_CREATED,
    IMPORT_CANCELED,
    PROMOTION_CREATED,
    PROMOTION_UPDATED,
    PROMOTION_ENABLED,
    PROMOTION_DISABLED,
    EXPENSE_CREATED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    STOCKTAKE_CREATED,
    STOCKTAKE_APPLIED,
    STOCKTAKE_CANCELED,
    SHIFT_OPENED,
    SHIFT_CLOSED,
    SHIFT_CLOSED_BY_MANAGER
}
